### ISSUE TITLE
how to generate the output file?

### ISSUE THREAD

**Issue by ozbillwang** [sbstjn/serverless-stack-output#13]
I followed the README and added plugin and custom parts in `serverless.yml` and I created  `scripts/output.js` from example.

Then I run `sls deploy`. 

No file `.build/stack.toml` was generated. 

Any steps I missed?

**Comment by DavideCrapa** [comment]
create a "output" folder and change the configuration to: 

output:
      handler: scripts/output.handler
      file: output/awsConfig..json

**Comment by ozbillwang** [comment]
Finally realised that the file `scripts/output.js` is not required at all. 

I knew the issue now, it looks a bug for me. This issue is only appeared when there is no change. 

If the stack has no change,

```
Serverless: Service files not changed. Skipping deployment...
```
I can't get the output json file. Is it true?  @DavideCrapa  @sbstjn 

I run the command `sls deploy` via CICD pipeline, my next build job need read this on-fly generated config file. If this file `output.json` is not generated, my next build job will fail. 

I can see `.serverless/output.json` file if there are updates.

**Secondly**, I want to export the output as new json file every time, if I run `sls info -v -s dev`, will this be possible?

**Comment by ozbillwang** [comment]
And not sure if this is related with this issue as well: https://github.com/sbstjn/serverless-stack-output/issues/25

**Comment by ozbillwang** [comment]
Ok, I got result. 

My problem can be fixed after I switch to plugin `'@anttiviljami/serverless-stack-output'`
