### ISSUE TITLE
feature required - output as shell source file

### ISSUE THREAD

**Issue by ozbillwang** [sbstjn/serverless-stack-output#5]
could I ask for a new format, that i can use the output as source file for shell script.

```bash
$ cat stack.sh

ExampleUserSecret="YourUserSecretKey"
ExampleUserKey="YourUserAccessKey"
```
Similar as `TOML` but no space around "="

so I can source it directly

    .  stack.sh

**Comment by sbstjn** [comment]
Good idea!

I usually use the JSON format and parse the needed values with `jq` …

```json
{
  "foo": "bar"
}
```

```bash
$ > cat output.json | jq '.foo' -r

bar
```

**Comment by ozbillwang** [comment]
Not sure, but let me dig it. 

And another request is, I prefer to generate the output.sh file and upload to s3 bucket directly. 

So in my containers, I can easily source it directly.

**Comment by ozbillwang** [comment]
I found another plugin, which can gerenate the env file 

https://github.com/Jimdo/serverless-dotenv?files=1
