### ISSUE TITLE
Add custom domain to output

### ISSUE THREAD

**Issue by balassy** [sbstjn/serverless-stack-output#6]
As a developer using the Serverless framework with the `serverless-domain-manager` plugin, I would like to have the name of my custom domain appear in the output file of the `serverless-stack-output` plugin, so I can target my post-deployment integration tests to the custom domain, instead of the API Gateway generated `ServiceEndpoint`.

Thank you for creating and maintaining this plugin!

**Comment by sbstjn** [comment]
Thanks for the issue. Basically, the plugin just takes the configured stack output and writes it to a file. You should open an issue for the `serverless-domain-manager` plugin to include the custom domain in the stack output. If this is implemented in the `serverless-domain-manager` plugin, my plugin will include the domain automatically …

**Comment by sbstjn** [comment]
I created an issue at https://github.com/sbstjn/serverless-stack-output/issues/6 🎉

**Comment by sbstjn** [comment]
I created an issue at https://github.com/amplify-education/serverless-domain-manager/issues/43 🎉

**Comment by balassy** [comment]
Thank you!

**Comment by kalinchernev** [comment]
Useful reply - I also came here after searching for a similar solution, but after configuring an ES.
Not too obvious from the documentation, but I guess anyone using a configuration or a plugin not providing the output will either read this guide here or read the example very carefully.

**Comment by majones-amplify** [comment]
Hi all!
I had a chance to resolve this this morning (https://github.com/amplify-education/serverless-domain-manager/pull/47), the plugin should now support this functionality.
Give it a whirl and please open an issue with us if you have any problems with it.

**Comment by balassy** [comment]
Thank you @majones-amplify, it works well from serverless-domain-manager@1.1.18.
This issue can be closed now.
